[[redirects]]
  from = "/post/:slug"
  to = "/.netlify/functions/readSinglePost?slug=:slug"
  status = 200
  force = true

[[redirects]]
  from = "/postdetail/:slug"
  to = "/.netlify/functions/readSinglePost?slug=:slug"
  status = 200
  force = true

[[redirects]]
  from = "/generate/*"
  to = "/.netlify/functions/generate-html"
  status = 200

[build]
  functions = "netlify/functions"
  publish = "dist"

