[[redirects]]
  from = "/post/:slug.html"
  to = "/.netlify/functions/readSinglePost?slug=:slug"
  status = 200
  force = true

[[redirects]]
  from = "/post/:slug"
  to = "/.netlify/functions/readSinglePost?slug=:slug"
  status = 200
  force = true
  
[[redirects]]
  from = "/postdetail/:slug"
  to = "/.netlify/functions/readSinglePost?slug=:slug"
  status = 200
  force = true

[[redirects]]
  from = "/generate/*"
  to = "/.netlify/functions/generate-html"
  status = 200


[[redirects]]
  from = "/saveFormsToStatic/*"
  to = "/.netlify/functions/saveFormsToStatic"
  status = 200

[[redirects]]
  from = "/staticIndexMaker/*"
  to = "/.netlify/functions/staticIndexMaker"
  status = 200


[[redirects]]
  from = "/forms/postForm"
  to = "/.netlify/functions/afterFormSubmitReaction"
  status = 200


[functions]
  included_files = ["netlify/functions/static-post-template.html"]
  node_bundler = "esbuild"



[[plugins]]
  package = "@netlify/plugin-functions-core"




[build]
  functions = "netlify/functions"
