[[redirects]]
  from = "/post/:slug"
  to = "/.netlify/functions/readSinglePost?slug=:slug"
  status = 200
  force = true

[[redirects]]
  from = "/postdetail/:slug"
  to = "/.netlify/functions/readSinglePost?slug=:slug"
  status = 200
  force = true

  
[build]
  functions = "netlify/functions"

[[plugins]]
package = "netlify-plugin-prerender"


